theme: jekyll-theme-cayman
url: https://logophoman.github.io/Java-Bootcamp/
title: Java Bootcamp SS20
fulltitle: Java Bootcamp - Let's learn Java
subtitle: für alle die Bock haben ein bisschen Java zu lernen – SoSe 2020
